@startuml Classes conceptuelles
header étape 1 - Classes conceptuelles
class Personne
class Assistant
class Professeur
class Etudiant
class Discipline
class Cours

Personne <|-- Assistant
Personne <|-- Professeur
Personne <|-- Etudiant
@enduml
